- name: Instalação de pacotes via apt
  apt:
    pkg:
      - kolourpaint
      - firmware-linux-nonfree
      - webext-ublock-origin-firefox
      - webext-ublock-origin-chromium
      - ntfs-3g
      - dosfstools
      - exfat-fuse
      - exfatprogs
      - chromium
      - vim
      - fonts-crosextra-carlito
      - fonts-crosextra-caladea
      - ttf-mscorefonts-installer
      - p7zip-full
      - p7zip-rar
      - gvfs-backends
      - gnome-disk-utility
      - zip
      - unzip
      - rar
      - unrar
      - pdftk

# Avaliar se precisamos desses pacotes:
#      - texlive-full
#      - texstudio-l10n
#      - praat
#      - texstudio
#      - inkscape
#      - gimp
#      - gimp-help-pt
#      - build-essential
#      - r-base
#      - gfortran
#      - terminator
#      - okular
#      - audacity
#      - vlc
#      - git


