- name: geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: 'America/Sao_Paulo'
    ntp_servers: "{{ proaluno_ntp_servers }}"

- name: Configura resolv.conf para consultar DNSs no pr√≥prio samba
  include_role:
    name: blackstar257.resolv
  vars:
    resolv_conf_nameservers: "{{ proaluno_ntp_servers }}"
    resolv_conf_search_domains:
      - "smbdomain.fflch.usp.br"